spring.datasource.url=jdbc:postgresql://localhost:5432/smecs
spring.datasource.username=postgres
spring.datasource.password=Bernardxx2003
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8080

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

spring.security.oauth2.client.registration.google.client-id=676308194726-f8cdpqv14aeet5qgi5jp88bl9ksb9bom.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
