spring.config.import=optional:file:.env
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:smecs}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Bernardxx2003}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8080

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

spring.security.oauth2.client.registration.google.client-id=676308194726-f8cdpqv14aeet5qgi5jp88bl9ksb9bom.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
